**Problem 1: ** 

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
lst = []
for i in range(1000):
    if (i % 3 == 0) or (i % 5 == 0):
        lst.append(i)
print(sum(lst))

233168

**Problem 2:**

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [14]:
fib = [1, 2]
i = 0
while fib[-1] <= 4000000:
    fib.append(fib[i] + fib[i + 1])
    i += 1
evens = []
for n in fib:
    if n % 2 == 0:
        evens.append(n)
print(fib)
print(evens)
print(sum(evens))

[1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887]
[2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]
4613732

**Problem 3:**

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [37]:
class Node:
    def __init__(self, val):
        self.left = None
        self.right = None
        self.val = val

In [89]:
prime_nums = []

for num in range(2, 5000):
    for i in range(2, num):
        if num % i == 0:
            break
        else:
            prime_nums.append(num)

In [90]:
prime_set = set(prime_nums)
list_prime = list(prime_set)
list_prime

[3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,
 353,
 355,
 357,
 359,
 361,
 363,
 365,
 367,
 369,
 371,
 373,
 375,
 377,
 379,
 381,
 383,
 385,
 387,
 389,
 391,
 393,
 395,
 397,
 399,
 401,
 403,
 405,
 407,
 409,
 411,
 413,
 415,
 417,
 419,
 421,
 423,
 425,
 427,
 429,
 431,
 433,
 435,
 437,
 439,
 441,
 443,
 445,
 447,
 449,
 451,
 453,
 455,
 457,
 459,
 461,
 463,
 465,
 467,
 469,
 471,
 473,
 475,
 477,
 479,
 481,
 483,
 485,
 487,
 489,
 491,
 493,
 495,
 497,
 499,
 501,
 503,
 505,
 507,
 509,
 511,
 513,
 515,
 517,
 519,
 521,
 523,
 525,
 527,
 529,
 531,
 533,
 535,
 537,
 539,
 541,
 543,
 545,
 547,
 549,
 551,
 553,
 555,
 557,
 559,
 561,
 563,
 565,
 567,
 569,
 571,
 573,
 575,
 577,
 579,
 581,
 583,
 585,
 587,
 589,
 591,
 593,
 595,
 597,
 599,
 601,
 603,
 605,
 607,
 609,
 611,
 613,
 615,
 617,
 619,
 621,
 623,
 625,
 627,
 629,
 631,
 633,
 635,
 637,
 639,
 641,
 643,
 645,
 647,
 649,
 651,
 653,
 655,
 657,
 659,
 661,
 663,
 665,
 667,
 669,
 671,
 673,
 675,
 677,
 679,
 681,
 683,
 685,
 687,
 689,
 691,
 693,
 695,
 697,
 699,
 701,
 703,
 705,
 707,
 709,
 711,
 713,
 715,
 717,
 719,
 721,
 723,
 725,
 727,
 729,
 731,
 733,
 735,
 737,
 739,
 741,
 743,
 745,
 747,
 749,
 751,
 753,
 755,
 757,
 759,
 761,
 763,
 765,
 767,
 769,
 771,
 773,
 775,
 777,
 779,
 781,
 783,
 785,
 787,
 789,
 791,
 793,
 795,
 797,
 799,
 801,
 803,
 805,
 807,
 809,
 811,
 813,
 815,
 817,
 819,
 821,
 823,
 825,
 827,
 829,
 831,
 833,
 835,
 837,
 839,
 841,
 843,
 845,
 847,
 849,
 851,
 853,
 855,
 857,
 859,
 861,
 863,
 865,
 867,
 869,
 871,
 873,
 875,
 877,
 879,
 881,
 883,
 885,
 887,
 889,
 891,
 893,
 895,
 897,
 899,
 901,
 903,
 905,
 907,
 909,
 911,
 913,
 915,
 917,
 919,
 921,
 923,
 925,
 927,
 929,
 931,
 933,
 935,
 937,
 939,
 941,
 943,
 945,
 947,
 949,
 951,
 953,
 955,
 957,
 959,
 961,
 963,
 965,
 967,
 969,
 971,
 973,
 975,
 977,
 979,
 981,
 983,
 985,
 987,
 989,
 991,
 993,
 995,
 997,
 999,
 1001,
 1003,
 1005,
 1007,
 1009,
 1011,
 1013,
 1015,
 1017,
 1019,
 1021,
 1023,
 1025,
 1027,
 1029,
 1031,
 1033,
 1035,
 1037,
 1039,
 1041,
 1043,
 1045,
 1047,
 1049,
 1051,
 1053,
 1055,
 1057,
 1059,
 1061,
 1063,
 1065,
 1067,
 1069,
 1071,
 1073,
 1075,
 1077,
 1079,
 1081,
 1083,
 1085,
 1087,
 1089,
 1091,
 1093,
 1095,
 1097,
 1099,
 1101,
 1103,
 1105,
 1107,
 1109,
 1111,
 1113,
 1115,
 1117,
 1119,
 1121,
 1123,
 1125,
 1127,
 1129,
 1131,
 1133,
 1135,
 1137,
 1139,
 1141,
 1143,
 1145,
 1147,
 1149,
 1151,
 1153,
 1155,
 1157,
 1159,
 1161,
 1163,
 1165,
 1167,
 1169,
 1171,
 1173,
 1175,
 1177,
 1179,
 1181,
 1183,
 1185,
 1187,
 1189,
 1191,
 1193,
 1195,
 1197,
 1199,
 1201,
 1203,
 1205,
 1207,
 1209,
 1211,
 1213,
 1215,
 1217,
 1219,
 1221,
 1223,
 1225,
 1227,
 1229,
 1231,
 1233,
 1235,
 1237,
 1239,
 1241,
 1243,
 1245,
 1247,
 1249,
 1251,
 1253,
 1255,
 1257,
 1259,
 1261,
 1263,
 1265,
 1267,
 1269,
 1271,
 1273,
 1275,
 1277,
 1279,
 1281,
 1283,
 1285,
 1287,
 1289,
 1291,
 1293,
 1295,
 1297,
 1299,
 1301,
 1303,
 1305,
 1307,
 1309,
 1311,
 1313,
 1315,
 1317,
 1319,
 1321,
 1323,
 1325,
 1327,
 1329,
 1331,
 1333,
 1335,
 1337,
 1339,
 1341,
 1343,
 1345,
 1347,
 1349,
 1351,
 1353,
 1355,
 1357,
 1359,
 1361,
 1363,
 1365,
 1367,
 1369,
 1371,
 1373,
 1375,
 1377,
 1379,
 1381,
 1383,
 1385,
 1387,
 1389,
 1391,
 1393,
 1395,
 1397,
 1399,
 1401,
 1403,
 1405,
 1407,
 1409,
 1411,
 1413,
 1415,
 1417,
 1419,
 1421,
 1423,
 1425,
 1427,
 1429,
 1431,
 1433,
 1435,
 1437,
 1439,
 1441,
 1443,
 1445,
 1447,
 1449,
 1451,
 1453,
 1455,
 1457,
 1459,
 1461,
 1463,
 1465,
 1467,
 1469,
 1471,
 1473,
 1475,
 1477,
 1479,
 1481,
 1483,
 1485,
 1487,
 1489,
 1491,
 1493,
 1495,
 1497,
 1499,
 1501,
 1503,
 1505,
 1507,
 1509,
 1511,
 1513,
 1515,
 1517,
 1519,
 1521,
 1523,
 1525,
 1527,
 1529,
 1531,
 1533,
 1535,
 1537,
 1539,
 1541,
 1543,
 1545,
 1547,
 1549,
 1551,
 1553,
 1555,
 1557,
 1559,
 1561,
 1563,
 1565,
 1567,
 1569,
 1571,
 1573,
 1575,
 1577,
 1579,
 1581,
 1583,
 1585,
 1587,
 1589,
 1591,
 1593,
 1595,
 1597,
 1599,
 1601,
 1603,
 1605,
 1607,
 1609,
 1611,
 1613,
 1615,
 1617,
 1619,
 1621,
 1623,
 1625,
 1627,
 1629,
 1631,
 1633,
 1635,
 1637,
 1639,
 1641,
 1643,
 1645,
 1647,
 1649,
 1651,
 1653,
 1655,
 1657,
 1659,
 1661,
 1663,
 1665,
 1667,
 1669,
 1671,
 1673,
 1675,
 1677,
 1679,
 1681,
 1683,
 1685,
 1687,
 1689,
 1691,
 1693,
 1695,
 1697,
 1699,
 1701,
 1703,
 1705,
 1707,
 1709,
 1711,
 1713,
 1715,
 1717,
 1719,
 1721,
 1723,
 1725,
 1727,
 1729,
 1731,
 1733,
 1735,
 1737,
 1739,
 1741,
 1743,
 1745,
 1747,
 1749,
 1751,
 1753,
 1755,
 1757,
 1759,
 1761,
 1763,
 1765,
 1767,
 1769,
 1771,
 1773,
 1775,
 1777,
 1779,
 1781,
 1783,
 1785,
 1787,
 1789,
 1791,
 1793,
 1795,
 1797,
 1799,
 1801,
 1803,
 1805,
 1807,
 1809,
 1811,
 1813,
 1815,
 1817,
 1819,
 1821,
 1823,
 1825,
 1827,
 1829,
 1831,
 1833,
 1835,
 1837,
 1839,
 1841,
 1843,
 1845,
 1847,
 1849,
 1851,
 1853,
 1855,
 1857,
 1859,
 1861,
 1863,
 1865,
 1867,
 1869,
 1871,
 1873,
 1875,
 1877,
 1879,
 1881,
 1883,
 1885,
 1887,
 1889,
 1891,
 1893,
 1895,
 1897,
 1899,
 1901,
 1903,
 1905,
 1907,
 1909,
 1911,
 1913,
 1915,
 1917,
 1919,
 1921,
 1923,
 1925,
 1927,
 1929,
 1931,
 1933,
 1935,
 1937,
 1939,
 1941,
 1943,
 1945,
 1947,
 1949,
 1951,
 1953,
 1955,
 1957,
 1959,
 1961,
 1963,
 1965,
 1967,
 1969,
 1971,
 1973,
 1975,
 1977,
 1979,
 1981,
 1983,
 1985,
 1987,
 1989,
 1991,
 1993,
 1995,
 1997,
 1999,
 2001,
 ...]

In [91]:
root = Node(600851475143)

for i in list_prime:
    if root.val % i == 0:
        break
root.left = Node(i)
root.right = Node(root.val / i)

if root.right.val.is_integer() == False:
    print("Largest prime factor is in root.")

for i in list_prime:
    if root.right.val % i == 0:
        break
root.right.left = Node(i)
root.right.right = Node(root.right.val / i)

if root.right.right.val.is_integer() == False:
    print("Largest prime factor is in root.right.")

for i in list_prime:
    if root.right.right.val % i == 0:
        break
root.right.right.left = Node(i)
root.right.right.right = Node(root.right.right.val / i)

if root.right.right.right.val.is_integer() == False:
    print("Largest prime factor is in root.right.right.")

for i in list_prime:
    if root.right.right.right.val % i == 0:
        break
root.right.right.right.left = Node(i)
root.right.right.right.right = Node(root.right.right.right.val / i)

if root.right.right.right.right.val.is_integer() == False:
    print("Largest prime factor is in root.right.right.right.")

Largest prime factor is in root.right.right.right.

In [92]:
root.right.right.right.val

6857.0

**Problem 4:**

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [104]:
num = 959

len(str(num))

reverse = []

reverse.append(str(num)[2])
reverse.append(str(num)[1])
reverse.append(str(num)[0])

bool(int("".join(reverse)) == num)

True

In [111]:
999*999

998001

In [108]:
for i in reversed(range(1,6)):
    print(i)

5
4
3
2
1

In [128]:
palindrome_list = []
for i in range(100,1000):
    for j in range(100,1000):
        num = i*j
        upper = len(str(num))
        reverse_num = []
        reverse_num.append(str(num)[upper - 1])
        if upper - 2 >= 0:
            reverse_num.append(str(num)[upper - 2])
        if upper - 3 >= 0:
            reverse_num.append(str(num)[upper - 3])
        if upper - 4 >= 0:
            reverse_num.append(str(num)[upper - 4])
        if upper - 5 >= 0:
            reverse_num.append(str(num)[upper - 5])
        if upper - 6 >= 0:
            reverse_num.append(str(num)[upper - 6])
        if bool(int("".join(reverse_num)) == num) == True:
            palindrome_list.append(num)

In [129]:
len(palindrome_list)

2470

In [130]:
palindrome_list.sort()

In [131]:
palindrome_list.pop()

906609

**Problem 5: **

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [153]:
for j in range(1,21):
    for i in range(2520,25000):
        truth_list = []
        if i % j == 0:
            truth_list.append(True)
        else:
            truth_list.append(False)
    if all(truth_list) == True:
            print(i)

24999
24999
24999

In [179]:
for i in range(1,3000):
    truth_list = []
    for j in range(1,11):
        if i % j == 0:
            truth_list.append(True)
        else:
            truth_list.append(False)
    if all(truth_list) == True:
        print(i)
        break

2520

In [180]:
for i in range(50000,1000000000):
    truth_list = []
    for j in range(1,21):
        if i % j == 0:
            truth_list.append(True)
        else:
            truth_list.append(False)
    if all(truth_list) == True:
        print(i)
        break

232792560

**Problem 6:**

The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [192]:
squares = []
total = []
for n in range(1,101):
    squares.append(n**2)
    total.append(n)

In [193]:
squares

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000]

In [194]:
total

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [195]:
sum_of_squares = sum(squares)
square_of_sum = sum(total)**2

print(sum_of_squares)
print(square_of_sum)

338350
25502500

In [196]:
difference = square_of_sum - sum_of_squares
print(difference)

25164150

**Problem 7:**

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [2]:
prime_nums = []
for num in range(2, 200000):
    truth_statement = []
    for i in range(2, num):
        if num % i == 0:
            truth_statement.append(False)
        else:
            truth_statement.append(True)
    if all(truth_statement) == True:
        prime_nums.append(num)

In [3]:
len(prime_nums)

17984

In [4]:
prime_nums[0:15]

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

In [6]:
prime_nums[10000]

104743

** Problem 8:**

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [8]:
digit = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450

In [11]:
str(digit)[]

'1'

In [13]:
products = []
for i in range(0,988):
    digit1 = str(digit)[i]
    digit2 = str(digit)[i+1]
    digit3 = str(digit)[i+2]
    digit4 = str(digit)[i+3]
    digit5 = str(digit)[i+4]
    digit6 = str(digit)[i+5]
    digit7 = str(digit)[i+6]
    digit8 = str(digit)[i+7]
    digit9 = str(digit)[i+8]
    digit10 = str(digit)[i+9]
    digit11 = str(digit)[i+10]
    digit12 = str(digit)[i+11]
    digit13 = str(digit)[i+12]
    
    products.append(int(digit1) * int(digit2) * int(digit3) * int(digit4) * int(digit5) * int(digit6) * int(digit7) * int(digit8) * int(digit9) * int(digit10) * int(digit11) * int(digit12) * int(digit13))
products.sort()
products.pop()

23514624000

**Problem 9:**

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [14]:
for a in range(1,600):
    for b in range(1,600):
        for c in range(1,600):
            if ((a**2) + (b**2)) == c**2:
                if a + b + c == 1000:
                    print(a)
                    print(b)
                    print(c)
                    break
print("The product is ", a*b*c)

200
375
425
375
200
425
The product is  214921799

**Problem 10:**

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

--my prime_nums code (cell X) took a long time to run for 200000, so I can only imagine 2000000. 

--Once I reran that code with a new range, I would sum(prime_nums)